### ISSUE TITLE
remove the bootstrap dependency

### ISSUE THREAD

**Issue by davinkevin** [jacqueslareau/angular-pnotify#9]
Hi, 

You define a dependency in your bower.json to bootstrap, but in a lots of case we don't use the official bootstrap package (for our case, we work with the SASS-Only or CSS-Only version)

Angular-Ui-Bootstrap require bootstrap CSS to be inserted, but they don't add this item to the dependency, letting us define the way we want to import bootstrap CSS.

Somethings could be done for that case ?

Thanks

**Comment by joariasl** [comment]
The same problem again, I'm using bootstrap-sass and additionally angular-pnotify inject bootstrap as its dependency, overriding bootstrap-sass.

**Comment by joariasl** [comment]
You can solve this problem adding the
```json
"ignoredDependencies": [
  "bootstrap"
]
```
syntax to your bower.json if you are using bootstrap-sass.

**Comment by joariasl** [comment]
You can solve this adding
```js
"overrides": {
  "bootstrap": {
    "main": []
  }
}
```
to you bower.json file.
